openapi: 3.0.4
info:
  title: 'DaryaBotApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /api/Chat:
    post:
      tags:
        - Chat
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatHistoryDto'
          text/json:
            schema:
              $ref: '#/components/schemas/ChatHistoryDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChatHistoryDto'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ChatResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
components:
  schemas:
    ChatHistoryDto:
      type: object
      properties:
        turns:
          type: array
          items:
            $ref: '#/components/schemas/ChatTurn'
          nullable: true
      additionalProperties: false
    ChatResponse:
      type: object
      properties:
        sender:
          type: string
          nullable: true
        text:
          type: string
          nullable: true
        imageUrl:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
      additionalProperties: false
    ChatTurn:
      type: object
      properties:
        role:
          type: string
          nullable: true
        content:
          type: string
          nullable: true
      additionalProperties: false